server:
  port: 2001

mybatis:
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  application:
    name: seata-order-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #服务注册中心地址
      config:
        server-addr: localhost:8848 #配置中心地址
        group: DEFAULT_GROUP
        file-extension: yaml #指定yaml格式的配置
        namespace: ecc8fc68-f2f9-4eb8-9541-a0bc068b5361
    alibaba:
      seata:
        # 这里是自定义的事务组
        tx-service-group: jie_tx_group

